version: "3.9"

services: 
  database:
    image: postgres
    container_name: chanimation-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wallace
      - POSTGRES_PASSWORD=wallace
      - POSTGRES_DB=chanimationDB
    volumes:
      - ./.docker/pgdata:/data/postgres
    
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - database
    

volumes:
  pgdata:
    driver: local